name: Python application

on:
  feature:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [push]

jobs:
  build:

    runs-on: [ubuntu-18.04, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: [3.5, 3.6, 3.7]
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint .
